package com.xiaowei.entity;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.SHOP_ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.NAME
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.DESCRIPTION
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.IMG_URL
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.PRICE
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.STOCK
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.STATUS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.CREATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.UPDATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.DETAILS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.ID
     *
     * @return the value of goods.ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.ID
     *
     * @param id the value for goods.ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.SHOP_ID
     *
     * @return the value of goods.SHOP_ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.SHOP_ID
     *
     * @param shopId the value for goods.SHOP_ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.NAME
     *
     * @return the value of goods.NAME
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.NAME
     *
     * @param name the value for goods.NAME
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.DESCRIPTION
     *
     * @return the value of goods.DESCRIPTION
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.DESCRIPTION
     *
     * @param description the value for goods.DESCRIPTION
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.IMG_URL
     *
     * @return the value of goods.IMG_URL
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.IMG_URL
     *
     * @param imgUrl the value for goods.IMG_URL
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.PRICE
     *
     * @return the value of goods.PRICE
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.PRICE
     *
     * @param price the value for goods.PRICE
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.STOCK
     *
     * @return the value of goods.STOCK
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.STOCK
     *
     * @param stock the value for goods.STOCK
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.STATUS
     *
     * @return the value of goods.STATUS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.STATUS
     *
     * @param status the value for goods.STATUS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.CREATED_AT
     *
     * @return the value of goods.CREATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.CREATED_AT
     *
     * @param createdAt the value for goods.CREATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.UPDATED_AT
     *
     * @return the value of goods.UPDATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.UPDATED_AT
     *
     * @param updatedAt the value for goods.UPDATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.DETAILS
     *
     * @return the value of goods.DETAILS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.DETAILS
     *
     * @param details the value for goods.DETAILS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}