package com.xiaowei.entity;

import java.util.Date;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.NAME
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.DESCRIPTION
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.IMG_URL
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.OWNER_USER_ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Long ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.STATUS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.CREATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.UPDATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.ID
     *
     * @return the value of shop.ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.ID
     *
     * @param id the value for shop.ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.NAME
     *
     * @return the value of shop.NAME
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.NAME
     *
     * @param name the value for shop.NAME
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.DESCRIPTION
     *
     * @return the value of shop.DESCRIPTION
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.DESCRIPTION
     *
     * @param description the value for shop.DESCRIPTION
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.IMG_URL
     *
     * @return the value of shop.IMG_URL
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.IMG_URL
     *
     * @param imgUrl the value for shop.IMG_URL
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.OWNER_USER_ID
     *
     * @return the value of shop.OWNER_USER_ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.OWNER_USER_ID
     *
     * @param ownerUserId the value for shop.OWNER_USER_ID
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.STATUS
     *
     * @return the value of shop.STATUS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.STATUS
     *
     * @param status the value for shop.STATUS
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.CREATED_AT
     *
     * @return the value of shop.CREATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.CREATED_AT
     *
     * @param createdAt the value for shop.CREATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.UPDATED_AT
     *
     * @return the value of shop.UPDATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.UPDATED_AT
     *
     * @param updatedAt the value for shop.UPDATED_AT
     *
     * @mbg.generated Mon Feb 22 14:54:25 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}